#ifndef FUNGAL_LLM_SIMPLE_HPP
#define FUNGAL_LLM_SIMPLE_HPP

#include <string>
#include <vector>
#include <map>
#include <memory>
#include <cmath>
#include <algorithm>
#include <iostream>

struct CodePattern {
    std::string code;
    double confidence;
    std::string domain;
    int age = 0;

    double current_confidence() const {
        return confidence * std::pow(0.95, age);
    }
};

class SimpleLLMNode {
public:
    std::string name;
    std::string domain;
    double expertise = 0.5;
    double energy = 100.0;
    double trust = 1.0;
    std::vector<CodePattern> patterns;

    SimpleLLMNode(const std::string& n) : name(n) {}

    void set_domain(const std::string& d) {
        domain = d;
    }

    void generate_pattern(const std::string& prompt) {
        if (domain.empty()) return;
        if (energy < 10) return;

        std::string code;
        if (domain == "Python") {
            code = "def " + name + "_func():\n    # " + prompt + "\n    return None";
        } else if (domain == "Java") {
            code = "public void " + name + "Method() {\n    // " + prompt + "\n}";
        } else if (domain == "Rust") {
            code = "fn " + name + "_fn() {\n    // " + prompt + "\n}";
        } else {
            code = "// Generated by " + name;
        }

        double conf = 0.5 + (expertise * 0.4);  // Better experts = higher confidence
        patterns.push_back({code, conf, domain, 0});
        energy -= 10;
    }

    void age_patterns() {
        for (auto& p : patterns) {
            p.age++;
        }
        // Remove very old patterns
        patterns.erase(
            std::remove_if(patterns.begin(), patterns.end(),
                          [](const CodePattern& p) { return p.current_confidence() < 0.1; }),
            patterns.end()
        );
    }

    void refine_pattern(const std::string& code, bool worked) {
        for (auto& p : patterns) {
            if (p.code.find(code.substr(0, 20)) != std::string::npos) {
                if (worked) {
                    p.confidence = std::min(1.0, p.confidence + 0.15);
                    expertise = std::min(1.0, expertise + 0.05);
                } else {
                    p.confidence = std::max(0.0, p.confidence - 0.3);
                }
            }
        }
    }

    std::string get_best_pattern() const {
        if (patterns.empty()) return "// No patterns available";
        const CodePattern* best = &patterns[0];
        for (const auto& p : patterns) {
            if (p.current_confidence() > best->current_confidence()) {
                best = &p;
            }
        }
        return best->code;
    }
};

class SimpleFungalLLM {
public:
    std::vector<std::shared_ptr<SimpleLLMNode>> nodes;
    double substrate_health = 1.0;

    std::shared_ptr<SimpleLLMNode> add_node(const std::string& name) {
        auto node = std::make_shared<SimpleLLMNode>(name);
        nodes.push_back(node);
        return node;
    }

    void round() {
        // Nodes generate
        for (auto& node : nodes) {
            if (node->energy > 20) {
                node->generate_pattern("optimize " + node->domain);
            }
        }

        // Nodes age patterns
        for (auto& node : nodes) {
            node->age_patterns();
        }

        // Update substrate based on average trust
        double avg_trust = 0;
        for (auto& node : nodes) {
            avg_trust += node->trust;
        }
        avg_trust /= nodes.size();

        if (avg_trust > 0.8) {
            substrate_health = std::min(1.0, substrate_health + 0.05);
        } else {
            substrate_health = std::max(0.0, substrate_health - 0.02);
        }

        // Restore energy based on substrate
        for (auto& node : nodes) {
            node->energy = std::min(100.0, node->energy + (substrate_health * 10));
        }
    }

    std::string collaborative_generate(const std::string& prompt, const std::string& target_domain) {
        // Find best expert
        SimpleLLMNode* best = nullptr;
        for (auto& node : nodes) {
            if (node->domain == target_domain) {
                if (!best || node->expertise > best->expertise) {
                    best = node.get();
                }
            }
        }

        if (!best && !nodes.empty()) {
            best = nodes[0].get();
        }

        if (!best) return "// No nodes available";

        best->generate_pattern(prompt);
        return best->get_best_pattern();
    }

    std::string consensus_code(const std::string& prompt) {
        std::map<std::string, int> votes;
        for (auto& node : nodes) {
            std::string best = node->get_best_pattern();
            votes[best]++;
        }

        std::string winner;
        int max_votes = 0;
        for (auto& [code, count] : votes) {
            if (count > max_votes) {
                max_votes = count;
                winner = code;
            }
        }

        return winner.empty() ? "// No consensus" : winner;
    }
};

#endif
